// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eavbkgftriwiqkermwuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhdmJrZ2Z0cml3aXFrZXJtd3V3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMTYxOTQsImV4cCI6MjA3MjY5MjE5NH0.NQthq9mGPS7LnkaCVsHPvRM_VyuEwtgalMaA5BKien4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});